version: "3"

services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379

  apisix:
    image: apache/apisix:latest
    depends_on:
      - etcd
    ports:
      - "9080:9080"  # HTTP port
      - "9443:9443"  # HTTPS port
      - "9180:9180"  # Admin API
    environment:
      - ETCD_HOST=http://etcd:2379

  dashboard:
    image: apache/apisix-dashboard:latest
    ports:
      - "9000:9000"
    environment:
      - APIX_HOST=http://apisix:9180/apisix/admin
      - APIX_KEY=edd1c9f034335f136f87ad84b625c8f1  # Admin API key
